config/routes.rb
Rails.application.routes.draw do

  resources :customer_registrations, only: [:index, :destroy]

  get 'notifications/' => 'notifications#index'

  post 'push_notification_address' => 'push_notification_address#create'

  put 'requests/save_booking_availability' => 'requests#save_booking_availability', as: :booking_availabilities
  get 'requests/add_booking_availability' => 'requests#add_booking_availability', as: :add_availability

  get 'requests/' => 'requests#index'
  put 'requests/toggle_active/:id' => 'requests#toggle_active', as: :toggle_active_request

  delete 'customer_app/request/:id' => 'customer_app#delete_request'
  delete 'customer_app/booking/:id' => 'customer_app#delete_booking'
  post 'customer_app/register'
  post 'customer_app/request_code'
  get 'customer_app/check_code'
  post 'customer_app/complete_account'
  post 'customer_app/request' => 'customer_app#create_request'
  get 'customer_app/booking_status'
  get 'customer_app/booking_availability'
  post 'customer_app/register_push_notification'

  get 'customer_debts/index'
  get 'customer_debts/increase'
  post 'customer_debts/increase_debt'
  get 'customer_debts/decrease/:id' => 'customer_debts#decrease', as: :customer_debts_decrease
  post 'customer_debts/decrease_debt/:id' => 'customer_debts#decrease_debt', as: :decrease_debt

  resources :expenses, except: [:show]
  resources :expense_types, except: [:show]
  get 'expenses/new_periodic' => 'expenses#new_periodic', as: :new_periodic_expense
  get 'expenses/edit_periodic/:id' => 'expenses#edit_periodic', as: :edit_periodic_expense

  get 'statistics/' => 'statistics#index'
  get 'statistics/general'
  get 'statistics/customers'
  get 'statistics/finance'

  resources :trips, only: [:index, :edit, :destroy]
  patch 'trips/:id/update_active_base' => 'trips#update_active_base', as: :update_active_base
  delete 'trips/wipe_distances/:id' => 'trips#wipe_distances', as: :wipe_distances
  post 'trips/create/:date' => 'trips#create', as: :create_trip
  patch 'trips/move_item/:id/:trip_id' => 'trips#move_item', as: :trip_move_item
  patch 'trips' => 'trips#update', as: :update_trip
  get 'trips/printable/:id' => 'trips#printable', as: :printable_trip
  get 'trips/status/:id' => 'trips#status', as: :trip_status
  post 'trips/notify_customers' => 'trips#notify_customers'

  get 'ironing/past' => 'ironing#past', as: :past_ironing
  resources :ironing, except: [:destroy, :update, :new]
  get 'ironing/new/:id' => 'ironing#new', as: :new_ironing
  get 'ironing/receipt/:id' => 'ironing#receipt', as: :ironing_receipt

  resources :categories

  resources :bookings, except: [:show]
  get 'bookings/delivery/:id' => 'bookings#delivery', as: :bookings_delivery
  post 'bookings/new_delivery/:id' => 'bookings#new_delivery', as: :new_delivery
  get 'bookings/past' => 'bookings#past', as: :past_bookings

  resources :services
  get 'services/edit_price/:id' => 'services#edit_price', as: :edit_price
  post 'services/update_price/:id' => 'services#update_price', as: :update_price

  patch 'staff/toggle_active/:id/:account_type' => 'staff#toggle_active', as: :toggle_active_account
  devise_for :staff
  resources :staff, except: [:destroy]
  get 'staff/appoint/:role/' => 'staff#appoint_index', as: :appoint_index
  post 'staff/appoint' => 'staff#appoint'
  get 'staff/edit_wage/:id/:account_type/' => 'staff#edit_wage', as: :edit_wage
  post 'staff/:id/:account_type/update_wage' => 'staff#update_wage', as: :update_wage
  get 'staff/:ironer_id/ironer_weekly_wage' => 'staff#ironer_weekly_wage', as: :ironer_weekly_wage

  root 'home#index'

  resources :settings, only: :index

  resources :addresses, except: [:destroy, :new]
  get 'customers/:id/add_address' => 'addresses#new', as: :add_address
  get 'customers/:id/edit_active_address' => 'addresses#edit_active', as: :edit_active_address
  post 'customers/:id/update_active_address' => 'addresses#update_active', as: :update_active_address

  post 'customers/:id/create_code' => 'customers#create_code', as: :create_code
  patch 'customers/update_customers_per_page' => 'customers#update_customers_per_page', as: :update_customers_per_page
  get 'customers/check_unique' => 'customers#check_unique', as: :check_unique
  get 'customers/inactive' => 'customers#inactive', as: :inactive_customers
  devise_for :customers, only: :sessions
  resources :customers

  post 'driver_api/upload_trip_status'
  post 'driver_api/receive'
  get 'driver_api/get_daily_trip'
end

app/models/service.rb
# Services offered by the company
class Service < ActiveRecord::Base
  has_many :booking_services
  belongs_to :category

  validates :name, presence: true, length: { maximum: 300 }
  validates :name, uniqueness: {
    message: 'already exists for that category',
    scope: :category_id,
    case_sensitive: false
  }
  validates :price, presence: true

  scope :all_system, -> { where category: Category.system }
  scope :non_system, -> { where.not category: Category.system }
  scope :all_active, -> { where active: true }

  def system?
    category == Category.system
  end

  # creates a new service with the same name to replace it; renames the old one
  # return value is boolean for success
  def update_price(new_price)
    new_svc = Service.new(name: name,
                          price: new_price,
                          active: active,
                          category: category)
    timestamp_name = name + " (expired at: #{DateTime.current})"

    update(name: timestamp_name, active: false) && new_svc.save
  end

  def deletable?
    booking_services.empty? && !system?
  end

  # special services, should always exist in the DB
  def self.ironing_per_hour
    Service.find_by!(name: 'Ironing per hour')
  end

  def self.missed_driver_fine
    Service.find_by!(name: 'Missed driver fine')
  end

  def self.washing_per_laundry
    Service.find_by!(name: 'Washing per laundry')
  end

  def self.minimum_charge
    Service.find_by!(name: 'Minimum charge')
  end

  def self.extra_charge
    Service.find_by!(name: 'Extra charge')
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update,
                                     :edit_price, :update_price, :destroy]

  # GET /services
  def index
    @services = Service.includes(:category, :booking_services)
                       .non_system
                       .all_active
                       .order(id: :desc)
    @editable_system_services = [
      Service.ironing_per_hour, Service.missed_driver_fine,
      Service.washing_per_laundry, Service.minimum_charge
    ]
  end

  # GET /services/1
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  def create
    @service = Service.new(new_service_params)
    if @service.system?
      render plain: 'Error: cannot create a system service.'
    elsif @service.save
      redirect_to @service, notice: 'Service was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /services/1
  def update
    return if edit_service_params['category_id'].to_i == Category.system.id

    if @service.system?
      redirect_to @service, alert: 'Error: cannot edit.'
    elsif @service.update(edit_service_params)
      redirect_to @service, notice: 'Service was successfully updated.'
    else
      render :edit
    end
  end

  # GET /services/1/edit_price
  def edit_price
    return if @service.active
    redirect_to services_url, alert: 'Error: cannot edit an inactive price.'
  end

  # POST /services/1/update_price
  def update_price
    old_name = @service.name
    if !@service.active
      redirect_to services_url,
                  alert: 'Error: cannot edit an inactive price.'
    elsif @service == Service.extra_charge
      redirect_to services_url,
                  alert: 'Error: cannot edit this service.'
    elsif @service.update_price(edit_price_param)
      redirect_to services_url,
                  notice: "#{old_name} price was successfully changed."
    else
      render :edit_price
    end
  end

  # DELETE /services/1
  def destroy
    return unless @service.deletable?
    @service.destroy
    redirect_to services_url, notice: 'Service was successfully deleted.'
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def edit_service_params
    params.require(:service).permit(:name, :category_id)
  end

  def new_service_params
    params.require(:service).permit(:name, :price, :category_id, :active)
  end

  def edit_price_param
    params.require(:service).permit(:price)[:price]
  end
end

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
    <% if @service.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

          <ul>
            <% @service.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, required: '' %>
    </div>
    <% if @service.new_record? %>
        <div class="field">
          <%= f.label :price, 'Price(£)' %><br>
          <%= f.text_field :price, type: :number, step: 0.01, required: '' %>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :category_id, 'Category' %><br>
      <%= f.select :category_id, options_from_collection_for_select(Category.non_system, 'id', 'name') %>
    </div>
    <%= f.hidden_field :active, value: true %>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/services/edit.html.erb
<h3>Editing <%= @service.name %></h3>

<%= render 'form' %>

<%= link_to services_path, class: 'btn btn-default active' do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Back to Services
<% end %>

app/views/services/edit_price.erb
<h3>Editing <%= @service.name %></h3>

<%= form_for @service, url: update_price_path, method: :post do |f| %>
    <% if @service.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

          <ul>
            <% @service.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p><b>Category: </b><%= @service.category.name %></p>
    <p><b>Current price: </b><%= to_gbp @service.price %></p>
    <div class="field">
      <%= f.label :price, 'New Price(£): ' %>
      <%= f.text_field :price, type: :number, step: 0.01, size: 6, required: '' %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<%= link_to services_path, class: 'btn btn-default active' do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Back to Services
<% end %>

app/views/services/index.html.erb
<br />
<%= link_to new_service_path, class: 'btn btn-default btn-lg active', role: 'button' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Service
<% end %>
<%= link_to categories_path, class: 'btn btn-default btn-lg active', role: 'button' do %>
    <span class="glyphicon glyphicon-folder-open"></span>
    Service categories
<% end %>
<br />

<h1>Listing services</h1>

<table class="table table-striped system-services" border="1">
  <thead>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
  <% @editable_system_services.each do |system_service| %>
      <tr>
        <td><strong><%= system_service.name %></strong></td>
        <td><%= to_gbp system_service.price %></td>
        <td><%= link_to edit_price_path(system_service), class: 'btn btn-default active', role: 'button' do %>
              <span class="glyphicon glyphicon-gbp"></span>
              Change price
          <% end %></td>
      </tr>
  <% end %>

  </tbody>
</table>

<table class="table table-striped non-system-services" border="1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= to_gbp(service.price) %></td>
        <td><%= link_to service.category.name, service.category %></td>
        <td><%= link_to edit_service_path(service), class: 'btn btn-default active', role: 'button' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              Edit details
        <% end %></td>
        <td><%= link_to edit_price_path(service), class: 'btn btn-default active', role: 'button' do %>
              <span class="glyphicon glyphicon-gbp"></span>
              Change price
        <% end %></td>
        <td>
          <% if service.deletable? %>
              <%= link_to service, method: :delete, data: { confirm: 'Are you sure?' },
                          class: 'btn btn-danger active', role: 'button' do %>
                  <span class="glyphicon glyphicon-remove"></span>
                  Delete
              <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

<%= link_to services_path, class: 'btn btn-default active' do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Back to Services
<% end %>

app/views/services/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= to_gbp(@service.price) %>
</p>

<p>
  <strong>Category:</strong>
  <%= @service.category.name %>
</p>

<% unless @service.system? %>
    <%= link_to 'Edit', edit_service_path(@service) %> |
<% end %>
<%= link_to 'Edit price', edit_price_path(@service) %> |
<%= link_to 'Back', services_path %>