config/routes.rb
Rails.application.routes.draw do

  resources :customer_registrations, only: [:index, :destroy]

  get 'notifications/' => 'notifications#index'

  post 'push_notification_address' => 'push_notification_address#create'

  put 'requests/save_booking_availability' => 'requests#save_booking_availability', as: :booking_availabilities
  get 'requests/add_booking_availability' => 'requests#add_booking_availability', as: :add_availability

  get 'requests/' => 'requests#index'
  put 'requests/toggle_active/:id' => 'requests#toggle_active', as: :toggle_active_request

  delete 'customer_app/request/:id' => 'customer_app#delete_request'
  delete 'customer_app/booking/:id' => 'customer_app#delete_booking'
  post 'customer_app/register'
  post 'customer_app/request_code'
  get 'customer_app/check_code'
  post 'customer_app/complete_account'
  post 'customer_app/request' => 'customer_app#create_request'
  get 'customer_app/booking_status'
  get 'customer_app/booking_availability'
  post 'customer_app/register_push_notification'

  get 'customer_debts/index'
  get 'customer_debts/increase'
  post 'customer_debts/increase_debt'
  get 'customer_debts/decrease/:id' => 'customer_debts#decrease', as: :customer_debts_decrease
  post 'customer_debts/decrease_debt/:id' => 'customer_debts#decrease_debt', as: :decrease_debt

  resources :expenses, except: [:show]
  resources :expense_types, except: [:show]
  get 'expenses/new_periodic' => 'expenses#new_periodic', as: :new_periodic_expense
  get 'expenses/edit_periodic/:id' => 'expenses#edit_periodic', as: :edit_periodic_expense

  get 'statistics/' => 'statistics#index'
  get 'statistics/general'
  get 'statistics/customers'
  get 'statistics/finance'

  resources :trips, only: [:index, :edit, :destroy]
  patch 'trips/:id/update_active_base' => 'trips#update_active_base', as: :update_active_base
  delete 'trips/wipe_distances/:id' => 'trips#wipe_distances', as: :wipe_distances
  post 'trips/create/:date' => 'trips#create', as: :create_trip
  patch 'trips/move_item/:id/:trip_id' => 'trips#move_item', as: :trip_move_item
  patch 'trips' => 'trips#update', as: :update_trip
  get 'trips/printable/:id' => 'trips#printable', as: :printable_trip
  get 'trips/status/:id' => 'trips#status', as: :trip_status
  post 'trips/notify_customers' => 'trips#notify_customers'

  get 'ironing/past' => 'ironing#past', as: :past_ironing
  resources :ironing, except: [:destroy, :update, :new]
  get 'ironing/new/:id' => 'ironing#new', as: :new_ironing
  get 'ironing/receipt/:id' => 'ironing#receipt', as: :ironing_receipt

  resources :categories

  resources :bookings, except: [:show]
  get 'bookings/delivery/:id' => 'bookings#delivery', as: :bookings_delivery
  post 'bookings/new_delivery/:id' => 'bookings#new_delivery', as: :new_delivery
  get 'bookings/past' => 'bookings#past', as: :past_bookings

  resources :services
  get 'services/edit_price/:id' => 'services#edit_price', as: :edit_price
  post 'services/update_price/:id' => 'services#update_price', as: :update_price

  patch 'staff/toggle_active/:id/:account_type' => 'staff#toggle_active', as: :toggle_active_account
  devise_for :staff
  resources :staff, except: [:destroy]
  get 'staff/appoint/:role/' => 'staff#appoint_index', as: :appoint_index
  post 'staff/appoint' => 'staff#appoint'
  get 'staff/edit_wage/:id/:account_type/' => 'staff#edit_wage', as: :edit_wage
  post 'staff/:id/:account_type/update_wage' => 'staff#update_wage', as: :update_wage
  get 'staff/:ironer_id/ironer_weekly_wage' => 'staff#ironer_weekly_wage', as: :ironer_weekly_wage

  root 'home#index'

  resources :settings, only: :index

  resources :addresses, except: [:destroy, :new]
  get 'customers/:id/add_address' => 'addresses#new', as: :add_address
  get 'customers/:id/edit_active_address' => 'addresses#edit_active', as: :edit_active_address
  post 'customers/:id/update_active_address' => 'addresses#update_active', as: :update_active_address

  post 'customers/:id/create_code' => 'customers#create_code', as: :create_code
  patch 'customers/update_customers_per_page' => 'customers#update_customers_per_page', as: :update_customers_per_page
  get 'customers/check_unique' => 'customers#check_unique', as: :check_unique
  get 'customers/inactive' => 'customers#inactive', as: :inactive_customers
  devise_for :customers, only: :sessions
  resources :customers

  post 'driver_api/upload_trip_status'
  post 'driver_api/receive'
  get 'driver_api/get_daily_trip'
end

app/models/statistics.rb
# Behind the statistics pages
module Statistics
  def self.growth_over_time(klass, step = 1, start_date = nil)
    data = klass.pluck(:created_at).map(&:to_date).sort
    data = data.drop_while { |d| d < start_date } if start_date
    range = (start_date || data.first)..(Time.zone.today + step)
    range.step(step).map do |date|
      period_data = data.take_while { |d| d <= date }
      data = data.drop(period_data.size)
      [date, period_data.size]
    end.to_h
  end

  def self.count_from_growth(growth)
    running_total = 0
    growth.to_a.sort_by(&:first).map do |date, amount|
      running_total += amount
      [date, running_total.round(2)]
    end.to_h
  end

  def self.count_over_time(klass, step = 1, start_date = nil)
    count_from_growth(growth_over_time(klass, step, start_date))
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def index
    @filters = ['', 'Ironing', 'Driver', 'Ironers'] + ExpenseType.pluck(:name)
  end

  def general
    step = (params[:period].to_i || 7)
    start_date = params[:start_date]&.to_date

    @booking_growth  = Statistics.growth_over_time(Booking, step, start_date)
    @customer_growth = Statistics.growth_over_time(Customer, step, start_date)

    @booking_count  = Statistics.count_over_time(Booking, step, start_date)
    @customer_count = Statistics.count_over_time(Customer, step, start_date)
  end

  def customers
    @customers = Customer.all.includes(
      bookings: { ironing: { booking_services: :service } }
    ).sort_by { |c| -c.bookings.size }
  end

  def finance
    @period = (params[:period].to_i || 7)
    start_date = params[:start_date]&.to_date

    profits = Expense.profits_in_period(start_date)
    if params[:filter].present?
      profits = profits.select { |name, _| name == params[:filter] }
    end

    sorted_dates = profits.values.flatten.map(&:date).sort
    start_date = sorted_dates.first + @period - 1
    end_date = sorted_dates.last + @period
    @date_period = (start_date..end_date).step(@period)

    # { name => [date, amount] }
    # the difference between two dates is step
    # if amount is between two dates, it is included in the _later_
    profits_periods_hash = profits.keys.map do |name|
      profits_array = profits[name].sort_by(&:date)
      [name, @date_period.map do |date|
        relevant = profits_array.take_while { |p| p.date <= date }
        profits_array = profits_array.drop(relevant.size)
        [date, relevant.sum(&:amount).round(2)]
      end.to_h]
    end.to_h

    # date => amount
    @expenses_growth = profits_periods_hash.values.reduce do |h1, h2|
      h1.merge(h2) { |_, a1, a2| (a1 + a2).round(2) }
    end

    # date => accumulated_amount_until_date
    @expenses_sum = Statistics.count_from_growth(@expenses_growth)

    # { date => { name => amount_in_date } }
    @date_breakdown = @date_period.map do |date|
      [date, profits_periods_hash.map do |name, date_values|
        [name, date_values[date]]
      end.to_h]
    end.to_h

    # { name => total_amount }
    @total_breakdown = @date_breakdown.values.reduce do |h1, h2|
      h1.merge(h2) { |_, a1, a2| (a1 + a2).round(2) }
    end
  end
end

app/views/statistics/_profit_breakdown.erb
<h1>
  <%= from %>
  <%= 'to ' + to.to_s if from != to %>
</h1>
<table class="table table-striped" border="1">
  <thead>
  <tr>
    <th>Name</th>
    <th>Amount</th>
  </tr>
  </thead>

  <tbody>
  <% breakdown.select{|_, amount| amount != 0}.each do |name, amount| %>
      <tr>
        <td><%= name %></td>
        <td><%= to_gbp amount %></td>
      </tr>
  <% end %>

  <tr>
    <td><b>Total</b></td>
    <td><b><%= to_gbp breakdown.values.sum %></b></td>
  </tr>
  </tbody>
</table>

app/views/statistics/customers.html.erb
<h3>Number of bookings statistic</h3>
<table class="table table-striped" border="1">
  <thead>
  <tr>
    <th>Number of bookings</th>
    <th>Total revenue</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Nickname</th>
    <th>Payment scheme</th>
    <th>Discount</th>
    <th colspan="1">Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.bookings.size %></td>
        <td><%= to_gbp customer.bookings.map{|b| b.ironing.total_cost}.sum %></td>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td class="nickname"><%= customer.nickname %></td>
        <td><%= customer.payment_scheme.humanize %></td>
        <td><%= customer.discount %>%</td>
        <td><%= link_to edit_customer_path(customer), class: 'btn btn-default active', role: 'button' do %>
            <span class="glyphicon glyphicon-pencil"></span>
            Edit
        <% end %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to statistics_path, class: 'btn btn-default active' do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Back to Statistics
<% end %>

app/views/statistics/finance.erb
<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>

<h1>Profit at end of each period</h1>
<%= line_chart @expenses_growth %>
<h1>Accumulated profit over time</h1>
<%= line_chart @expenses_sum %>

<%= render 'profit_breakdown', breakdown: @total_breakdown,
           from: @date_period.to_a.first - @period + 1, to: @date_period.to_a.last %>

<% @date_period.each do |date| %>
    <%= render 'profit_breakdown', breakdown: @date_breakdown[date],
               from: date - @period + 1, to: date %>
<% end %>

<%= link_to statistics_path, class: 'btn btn-default active' do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Back to Statistics
<% end %>

app/views/statistics/general.erb
<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>

<h1>New bookings over time</h1>
<%= line_chart @booking_growth %>
<h1>New customers over time</h1>
<%= line_chart @customer_growth %>

<h1>Total bookings over time</h1>
<%= line_chart @booking_count %>
<h1>Total customers over time</h1>
<%= line_chart @customer_count %>

<%= link_to statistics_path, class: 'btn btn-default active' do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Back to Statistics
<% end %>

app/views/statistics/index.html.erb
<br />
<fieldset class="bordered">
  <form action="<%= statistics_general_path %>" method="get">
    <div class="field">
      <%= label_tag :period, 'Period duration (days)' %><br />
      <%= text_field_tag :period, '7' %>
      <br />
      <%= label_tag :start_date, 'Start date (leave blank to show from start)' %><br />
      <%= text_field_tag :start_date %>
      <br /><br />
      <%= button_tag name: nil, type: 'submit', class: 'btn btn-info active' do %>
          <span class="glyphicon glyphicon-globe"></span>
          General Statistics
      <% end %>
    </div>
  </form>
</fieldset>

<fieldset class="bordered">
  <form action="<%= statistics_finance_path %>" method="get">
    <div class="field">
      <%= label_tag :filter %><br />
      <%= select_tag :filter, options_for_select(@filters) %>
      <br />
      <%= label_tag :period, 'Period duration (days)' %><br />
      <%= text_field_tag :period, '7', id: 'finance_period' %>
      <br />
      <%= label_tag :start_date, 'Start date (leave blank to show from start)' %><br />
      <%= text_field_tag :start_date, '', id: 'finance_start_date' %>
      <br /><br />
      <%= button_tag name: nil, type: 'submit', class: 'btn btn-info active' do %>
          <span class="glyphicon glyphicon-gbp"></span>
          Finance Statistics
      <% end %>
    </div>
  </form>
</fieldset>

<fieldset class="bordered">
  <%= link_to statistics_customers_path, class: 'btn btn-info active', role: 'button' do %>
      <span class="glyphicon glyphicon-user"></span>
      Customer Statistics
  <% end %>
</fieldset>