config/routes.rb
Rails.application.routes.draw do

  resources :customer_registrations, only: [:index, :destroy]

  get 'notifications/' => 'notifications#index'

  post 'push_notification_address' => 'push_notification_address#create'

  put 'requests/save_booking_availability' => 'requests#save_booking_availability', as: :booking_availabilities
  get 'requests/add_booking_availability' => 'requests#add_booking_availability', as: :add_availability

  get 'requests/' => 'requests#index'
  put 'requests/toggle_active/:id' => 'requests#toggle_active', as: :toggle_active_request

  delete 'customer_app/request/:id' => 'customer_app#delete_request'
  delete 'customer_app/booking/:id' => 'customer_app#delete_booking'
  post 'customer_app/register'
  post 'customer_app/request_code'
  get 'customer_app/check_code'
  post 'customer_app/complete_account'
  post 'customer_app/request' => 'customer_app#create_request'
  get 'customer_app/booking_status'
  get 'customer_app/booking_availability'
  post 'customer_app/register_push_notification'

  get 'customer_debts/index'
  get 'customer_debts/increase'
  post 'customer_debts/increase_debt'
  get 'customer_debts/decrease/:id' => 'customer_debts#decrease', as: :customer_debts_decrease
  post 'customer_debts/decrease_debt/:id' => 'customer_debts#decrease_debt', as: :decrease_debt

  resources :expenses, except: [:show]
  resources :expense_types, except: [:show]
  get 'expenses/new_periodic' => 'expenses#new_periodic', as: :new_periodic_expense
  get 'expenses/edit_periodic/:id' => 'expenses#edit_periodic', as: :edit_periodic_expense

  get 'statistics/' => 'statistics#index'
  get 'statistics/general'
  get 'statistics/customers'
  get 'statistics/finance'

  resources :trips, only: [:index, :edit, :destroy]
  patch 'trips/:id/update_active_base' => 'trips#update_active_base', as: :update_active_base
  delete 'trips/wipe_distances/:id' => 'trips#wipe_distances', as: :wipe_distances
  post 'trips/create/:date' => 'trips#create', as: :create_trip
  patch 'trips/move_item/:id/:trip_id' => 'trips#move_item', as: :trip_move_item
  patch 'trips' => 'trips#update', as: :update_trip
  get 'trips/printable/:id' => 'trips#printable', as: :printable_trip
  get 'trips/status/:id' => 'trips#status', as: :trip_status
  post 'trips/notify_customers' => 'trips#notify_customers'

  get 'ironing/past' => 'ironing#past', as: :past_ironing
  resources :ironing, except: [:destroy, :update, :new]
  get 'ironing/new/:id' => 'ironing#new', as: :new_ironing
  get 'ironing/receipt/:id' => 'ironing#receipt', as: :ironing_receipt

  resources :categories

  resources :bookings, except: [:show]
  get 'bookings/delivery/:id' => 'bookings#delivery', as: :bookings_delivery
  post 'bookings/new_delivery/:id' => 'bookings#new_delivery', as: :new_delivery
  get 'bookings/past' => 'bookings#past', as: :past_bookings

  resources :services
  get 'services/edit_price/:id' => 'services#edit_price', as: :edit_price
  post 'services/update_price/:id' => 'services#update_price', as: :update_price

  patch 'staff/toggle_active/:id/:account_type' => 'staff#toggle_active', as: :toggle_active_account
  devise_for :staff
  resources :staff, except: [:destroy]
  get 'staff/appoint/:role/' => 'staff#appoint_index', as: :appoint_index
  post 'staff/appoint' => 'staff#appoint'
  get 'staff/edit_wage/:id/:account_type/' => 'staff#edit_wage', as: :edit_wage
  post 'staff/:id/:account_type/update_wage' => 'staff#update_wage', as: :update_wage
  get 'staff/:ironer_id/ironer_weekly_wage' => 'staff#ironer_weekly_wage', as: :ironer_weekly_wage

  root 'home#index'

  resources :settings, only: :index

  resources :addresses, except: [:destroy, :new]
  get 'customers/:id/add_address' => 'addresses#new', as: :add_address
  get 'customers/:id/edit_active_address' => 'addresses#edit_active', as: :edit_active_address
  post 'customers/:id/update_active_address' => 'addresses#update_active', as: :update_active_address

  post 'customers/:id/create_code' => 'customers#create_code', as: :create_code
  patch 'customers/update_customers_per_page' => 'customers#update_customers_per_page', as: :update_customers_per_page
  get 'customers/check_unique' => 'customers#check_unique', as: :check_unique
  get 'customers/inactive' => 'customers#inactive', as: :inactive_customers
  devise_for :customers, only: :sessions
  resources :customers

  post 'driver_api/upload_trip_status'
  post 'driver_api/receive'
  get 'driver_api/get_daily_trip'
end

app/models/ironing.rb
# Ironing-related parts of a booking
class Ironing < ActiveRecord::Base
  belongs_to :booking
  has_many   :booking_services, dependent: :destroy
  has_many   :ironing_tasks

  accepts_nested_attributes_for :booking_services, allow_destroy: true
  accepts_nested_attributes_for :ironing_tasks, allow_destroy: true

  def save_form(params, minimum_charge, ironer_mode)
    self.attributes = params
    save_success = save
    if save_success
      if minimum_charge
        apply_minimum_charge
      else
        remove_minimum_charge
      end

      if ironer_mode && booking.flat_rate?
        # mark as needing_extra_input unless it's already marked or filled
        unless booking_services.exists?(service: Service.ironing_per_hour)
          booking_services.create(service: Service.ironing_per_hour, count: 0.0)
        end
      end
    end
    save_success
  end

  # Total cost of the booking_services
  def total_cost
    booking_services.select { |bs| bs.id.present? }.map(&:total_cost).sum
  end

  # returns true only if was eligible but not applied
  def minimum_charge_skipped?
    mc = Service.minimum_charge
    (total_cost < mc.price &&
     booking_services.where(service: mc).empty?)
  end

  def apply_minimum_charge
    remove_minimum_charge

    min_charge_svc = Service.minimum_charge
    # exclude other minimum charge services
    cost = booking_services.where.not(service_id: min_charge_svc.id)
                           .map(&:total_cost)
                           .sum
    remaining = min_charge_svc.price - cost
    min_svc_count = remaining / min_charge_svc.price
    return unless remaining > 0
    booking_services.create(service: min_charge_svc,
                            count: min_svc_count,
                            discount: 0)
  end

  def remove_minimum_charge
    booking_services.where(service: Service.minimum_charge).destroy_all
  end

  def customer_name
    booking.customer.nickname
  end

  def ironed?
    !date_ironed.nil?
  end

  # query ironings which are not yet delivered
  # returns two arrays of Ironing [ironed, ready_for_ironing]
  # sorted ascending by date of creation
  def self.pending(*incl)
    ti = TripItem.joins(:trip).where(trips: { completed: false }).pluck(:id)
    ironings = Ironing.joins(:booking)
                      .includes(*incl)
                      .where(bookings: { delivery_trip_item_id: (ti + [nil]) })
                      .where.not(bookings: { collection_trip_item_id: ti })
                      .order(:id)
    ironings.partition(&:ironed?)
  end

  # part of ironed are returned as needing_extra_input
  def self.ironed_to_administrative(ironed)
    nei_ids = BookingService.where(ironing_id: ironed.map(&:id),
                                   count: 0,
                                   service_id: Service.ironing_per_hour.id)
                            .pluck(:ironing_id)
                            .uniq
    ironed.partition { |i| nei_ids.include?(i.id) }
  end

  self.per_page = 20

  def self.all_past(date_range)
    joins(booking: { delivery_trip_item: :trip })
      .where(trips: { completed: true, date: date_range })
      .order('trips.date DESC, created_at DESC')
  end
end

app/controllers/ironing_controller.rb
class IroningController < ApplicationController
  before_action :set_ironing, only: [:show, :receipt, :new, :edit]

  OWNER_ONLY_PAGES = [:receipt, :show, :past].freeze
  skip_before_action :authenticate_owner!,  except: OWNER_ONLY_PAGES
  before_action      :authenticate_ironer!, except: OWNER_ONLY_PAGES

  # GET /ironing
  def index
    @ironed, @ready_for_ironing = Ironing.pending(
      ironing_tasks: { ironer_account: :staff },
      booking: :customer
    )
    return if @ironer_mode
    @needing_extra_input, @ironed = Ironing.ironed_to_administrative(@ironed)
  end

  # GET /ironing/past
  def past
    page = (params[:page]&.to_i || 1)
    from = (params[:from_date]&.to_date || '2000-01-01'.to_date)
    to   = (params[:to_date]&.to_date   || Time.zone.today + 40.years)
    @ironed = Ironing.all_past(from..to).page(page)
                     .includes(booking:
                                 { customer: [],
                                   delivery_trip_item: :trip },
                               ironing_tasks:
                                 { ironer_account: :staff })
    render action: 'index'
  end

  # GET /ironing/new/:state_2_id (collected)
  # transition to state 3 (ironed)
  def new
    @ironer_accounts = IronerAccount.all_active.includes(:staff)
    @ironing_tasks = @ironing.ironing_tasks.build

    svc = if @ironing.booking.flat_rate?
            Service.ironing_per_hour
          else
            nil
          end
    @ironing_items = @ironing.booking_services.build(service: svc)
    @minimum_charge_checked = true
    @ironing = @ironing.decorate
  end

  # POST /ironing
  # reached from new and edit, technically works as update
  def create
    @ironing = Ironing.find(params[:ironing][:id])
    if @ironing.save_form(ironing_params, params[:minimum_charge], @ironer_mode)
      redirect_to ironing_index_path, notice: 'Ironing was successfully saved.'
    else
      @ironing = @ironing.decorate
      render action: 'new', id: params[:id]
    end
  end

  # GET /ironing/:state_2_or_3_id
  def show
    @ironing_items = @ironing.booking_services
                             .where.not(service: Service.all_system)
  end

  # GET /ironing/receipt/:state_3_id
  def receipt
  end

  # GET /ironing/:state_3_id/edit
  # posts to /ironing/create
  def edit
    @ironing_tasks = @ironing.ironing_tasks.includes(:ironer_account)
    inactive_used_accounts = @ironing_tasks.map(&:ironer_account)
                                           .uniq
                                           .reject(&:active)
    @ironer_accounts = IronerAccount.all_active + inactive_used_accounts

    if @ironing.booking.flat_rate?
      @ironing.booking_services.where(
        service: Service.ironing_per_hour
      ).first_or_initialize
    end
    @ironing_items = @ironing.booking_services

    if @ironer_mode
      @ironing_items = @ironing_items.where(
        service: Service.all_active.non_system
      )
    end
    @minimum_charge_checked = !@ironing.minimum_charge_skipped?
    @ironing = @ironing.decorate
  end

  def ironing_params
    par = params.require(:ironing).permit(
      :bag_count, :has_hangers, :date_ironed, :minimum_charge,
      booking_services_attributes:
        [:id, :service_id, :count, :discount, :_destroy],
      ironing_tasks_attributes:
        [:id, :ironer_account_id, :minutes_ironed, :_destroy]
    )
    par[:bag_count] ||= 0
    # convert input in time string format to minutes int format
    # example: "02:40" -> 160
    par[:ironing_tasks_attributes]&.each do |key, values|
      time = Time.zone.parse(values[:minutes_ironed])
      par[:ironing_tasks_attributes][key][:minutes_ironed] =
        time.hour * 60 + time.min
    end
    par
  end

  private

  def set_ironing
    @ironing = Ironing.find(params[:id])
  end
end

app/views/ironing/_booking_service_fields.html.erb
<div class="nested-fields">
  <%= f.input :service_id, as: :grouped_select, collection: categories,
              group_method: :last, required: true, input_html: { class: 'service-select' } %>
  <%= f.input :count, html: { step: :any }, required: true %>
  <% unless @ironer_mode %>
  <%= f.input :discount, label: 'Discount (%)', input_html:
      { step: :any, value: (f.object.discount || f.object.ironing.booking.discount || 0) } %>
  <% end %>
  <% if f.object.new_record? %>
      <%= link_to_remove_association 'X', f, class: 'btn btn-default active', role: 'button' %>
  <% else %>
      <%= f.input :_destroy, as: :boolean, label: 'Delete' %>
  <% end %>
</div>

app/views/ironing/_form.html.erb
<%= simple_form_for @ironing, url: ironing_index_path, method: :post do |f| %>
    <% if @ironing.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@ironing.errors.count, "error") %> prohibited this order from being saved:</h2>

          <ul>
            <% @ironing.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.hidden_field :id, value: params['id'] %>
    <%= f.fields_for :ironing_tasks, @ironing_tasks do |task_form| %>
        <%= render partial: 'ironing_task_fields',
                   locals: { f: task_form, ironer_accounts: @ironer_accounts, x_button: false }  %>
    <% end %>
    <div id="extra-ironing-tasks">
      <%= link_to_add_association '+', f, :ironing_tasks,
                                  render_options: {
                                      locals: {
                                          ironer_accounts: @ironer_accounts,
                                          x_button: true
                                      }
                                  },
                                  class: 'btn btn-default active', role: 'button' %>
    </div>
    <br />
    <%= f.input :bag_count, input_html: { step: 1 }, required: true %>
    <%= f.input :has_hangers %>

    <% if !@ironing.ironed? %>
        <%= f.input :date_ironed, as: :hidden, input_html: { value: Date.today } %>
    <% elsif !@ironer_mode %>
        <%= f.input :date_ironed, as: :string %>
    <% end %>

    <% if @ironer_mode %>
        <%= hidden_field_tag 'minimum_charge', @minimum_charge_checked %>
    <% else %>
        <div class="checkbox">
          <label for="minimum_charge">
            <%= check_box_tag 'minimum_charge', 1, @minimum_charge_checked %>
            Apply minimum charge
          </label>
        </div>
    <% end %>

    <script>window.paymentScheme = "<%= @ironing.booking.payment_scheme %>";</script>

    <% unless @ironer_mode and @ironing.booking.flat_rate? %>
    <div id="existing-booking-services">
      <%= f.fields_for :booking_services, @ironing_items do |bs| %>
          <% if bs.object.service_id == Service.ironing_per_hour.id %>
              <div class="nested-fields">
                <%= bs.input :service_id, as: :hidden %>
                <b>Service </b><br />
                <h4>Ironing per hour</h4>
                <p><b><abbr title="required">*</abbr> Time ironed (hours:minutes)</b></p>
                <%= bs.input :count,
                             as: :hidden,
                             input_html: { class: 'ironing_per_hour_float' },
                             required: true %>
                <div class="form-group float required booking_booking_services_count">
                  <input id="ironing_per_hour_field" class="string required form-control"
                         required="required" type="text"
                         value="<%= hours_float_to_s(bs.object.count) %>" />
                </div>
                <%= bs.input :discount,
                             label: 'Discount (%)',
                             input_html: {
                                 step: :any,
                                 value: (bs.object.discount ||
                                         bs.object.ironing.booking.discount ||
                                         0)
                             }
                %>
              </div>
          <% elsif bs.object.service_id == Service.minimum_charge.id %>
              <div class="nested-fields">
                <b>Service </b><br />
                <h4>Minimum charge fee</h4>
                <b>Cost </b><br />
                <h4><%= to_gbp(bs.object.total_cost) %></h4>
              </div>
          <% else %>
              <%= render partial: 'booking_service_fields',
                         locals: { f: bs, categories: @ironing.categories(@ironer_mode) }  %>
          <% end %>
      <% end %>
    </div>
    <div id="extra-booking-services">
      <%= link_to_add_association '+', f, :booking_services,
                                  render_options: {
                                      locals: {
                                          categories: @ironing.categories(@ironer_mode)
                                      }
                                  },
                                  class: 'btn btn-default active', role: 'button' %>
    </div>
    <% end %>

    <div class="actions">
      <br />
      <%= f.button :button do %>
          <% if @ironing.ironed? %>
              <span class="glyphicon glyphicon-floppy-saved"></span>
          <% else %>
              <span class="glyphicon glyphicon-floppy-disk"></span>
          <% end %>
          Submit ironing
      <% end %>
    </div>
<% end %>

<%= link_to ironing_index_path, class: 'btn btn-default active' do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Back to Ironing
<% end %>

app/views/ironing/_ironing_task_fields.erb
<div class="nested-fields">
  <%= f.input :ironer_account_id, collection: ironer_accounts,
                      label_method: :full_name, required: true %>
  <%= f.input :minutes_ironed, as: :string,
                      input_html: { value: minutes_int_to_s(f.object.minutes_ironed),
                                    class: 'ironing_task_time_ironed' },
                      label: 'Time ironed (hours:minutes)', required: true %>
  <% if !f.object.new_record? %>
      <%= f.input :_destroy, as: :boolean, label: 'Delete' %>
  <% elsif x_button %>
      <%= link_to_remove_association 'X', f, class: 'btn btn-default active', role: 'button' %>
  <% end %>
</div>

app/views/ironing/edit.html.erb
<h3>Edit ironing for <%= link_to @ironing.customer_name, @ironing.booking.customer %></h3>

<%= render 'form' %>

app/views/ironing/index.html.erb
<% if action_name == 'index' %>

<% unless @ironer_mode %>
    <%= link_to past_ironing_path, class: 'btn btn-default btn-lg active', role: 'button' do %>
        <span class="glyphicon glyphicon-folder-open"></span>
        Past ironing
    <% end %>
<% end %>
<br />
<h2>Ready for ironing</h2>

<table id="orders-table" class="table table-striped" border="1">
  <thead>
  <tr>
    <th>Customer</th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
  <% @ready_for_ironing.each do |ironing| %>
      <tr>
        <td><%= link_to ironing.booking.customer.nickname,
                        ironing.booking.customer %></td>
        <td><%= link_to new_ironing_path(ironing),
                        class: 'btn btn-default btn-lg active', role: 'button' do %>
              <span class="glyphicon glyphicon-plus"></span>
              Add information
        <% end %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<% unless @ironer_mode %>
<h2>Need extra information</h2>

<table class="table table-striped" border="1">
  <thead>
  <tr>
    <th>Customer</th>
    <th>Ironer</th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
  <% @needing_extra_input.each do |ironing| %>
      <tr>
        <td><%= link_to ironing.booking.customer.nickname, ironing.booking.customer %></td>
        <td><%= safe_join(ironing.ironing_tasks.map(&:ironer_account).map do |ironer|
            link_to ironer.full_name, ironer.staff
          end, ', ')
        %></td>
        <td><%= link_to edit_ironing_path(ironing),
                        class: 'btn btn-default active', role: 'button' do %>
              <span class="glyphicon glyphicon-plus"></span>
              Add extra information
        <% end %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<% end %>

<h2>Ironed</h2>

<% elsif action_name == 'past' %>
    <h2>Past Ironing</h2>
    <form action="<%= past_bookings_path %>" method="get">
      <div class="field">
        <%= text_field_tag :from_date, nil, placeholder: 'From' %>
        <%= text_field_tag :to_date, nil, placeholder: 'To' %>
        <%= button_tag name: nil, type: 'submit', class: 'btn btn-default active' do %>
            <span class="glyphicon glyphicon-search"></span>
            &nbsp
            Search
        <% end %>
      </div>
    </form>
<% end %>

<table id="ironed-table" class="table table-striped" border="1">
  <thead>
  <tr>
    <th>Customer</th>
    <th>Ironer</th>
    <% if action_name == 'past' %>
        <th>Date delivered</th>
    <% end %>
    <th colspan="<%= if @ironer_mode then 1 else 3 end %>"></th>
  </tr>
  </thead>

  <tbody>
  <% @ironed.each do |ironing| %>
      <tr>
        <td><%= link_to ironing.booking.customer.nickname, ironing.booking.customer %></td>
        <td><%= safe_join(ironing.ironing_tasks.map(&:ironer_account).map do |ironer|
            link_to ironer.full_name, ironer.staff
          end, ', ')
        %></td>
        <% if action_name == 'past' %>
            <td><%= ironing.booking.delivery_trip_item.trip.date %></td>
        <% end %>
        <td><%= link_to edit_ironing_path(ironing), class: 'btn btn-default active', role: 'button' do %>
              <span class="glyphicon glyphicon-pencil"></span>
              Edit
        <% end %></td>
        <% unless @ironer_mode %>
            <td><%= link_to ironing_receipt_path(ironing),
                            class: 'btn btn-default active', role: 'button' do %>
                  <span class="glyphicon glyphicon-list-alt"></span>
                  Receipt
            <% end %></td>

            <td><%= link_to ironing, class: 'btn btn-default active', role: 'button' do %>
                  <span class="glyphicon glyphicon-th-list"></span>
                  Show
            <% end %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<% if action_name == 'past' %>
    <div class="digg_pagination">
      <%= will_paginate @ironed %>
    </div>
    <%= link_to ironing_index_path, class: 'btn btn-default active' do %>
        <span class="glyphicon glyphicon-arrow-left"></span>
        Back to Ironing
    <% end %>
<% end %>
<br />

app/views/ironing/new.html.erb
<h3>Ironing for <%= link_to @ironing.customer_name, @ironing.booking.customer %></h3>

<%= render 'form' %>

app/views/ironing/receipt.html.erb
<br />

<p>
  <strong>Customer:</strong>
  <%= @ironing.customer_name %>
</p>

<% @ironing.booking_services.each do |bs| %>
    <p>
      <strong>Item:</strong>
      <%= bs.service.name %>
    <br />
      <strong>Cost per item:</strong>
      <%= to_gbp bs.service.price %>
    <% if bs.discount != 0 %>
      <br />
        <strong>Discount:</strong>
        <%= number_to_percentage(bs.discount, { strip_insignificant_zeros: true }) %>
    <% end -%>
    <br />
      <strong>Count:</strong>
      <%= bs.count.prettify %>
    <br />
      <strong>Cost:</strong>
      <%= to_gbp bs.total_cost %>
    </p>
<% end %>
<p>
  <strong>Total cost:</strong>
  <%= to_gbp @ironing.total_cost %>
</p>

<%= link_to ironing_index_path, class: 'btn btn-default active' do %>
    <span class="glyphicon glyphicon-arrow-left"></span>
    Back to Ironing
<% end %>
<br />
<%= link_to edit_ironing_path(@ironing), class: 'btn btn-default active' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit Ironing
<% end %>

app/views/ironing/show.html.erb
<p>
  <strong>Customer:</strong>
  <%= @ironing.customer_name %>
</p>

<% if @ironing.ironed? %>
    <p>
      <strong>Ironing tasks:</strong>
      <% @ironing.ironing_tasks.each do |task| %>
        <p>
          <strong>* Ironer:</strong>
          <%= task.ironer_account.full_name %>
        </p>
        <p>
          <strong>* Time ironed:</strong>
          <%= minutes_int_to_s task.minutes_ironed %>
        </p>
      <% end %>
    </p>
    <p>
      <strong>Number of bags:</strong>
      <%= @ironing.bag_count %>
    </p>
    <p>
      <strong>Hangers?:</strong>
      <%= yes_no @ironing.has_hangers? %>
    </p>

    <% @ironing_items.each do |bs| %>
        <p>
          <strong>Item:</strong>
          <%= bs.service.name %>
        </p>
        <p>
          <strong>Count:</strong>
          <%= bs.count %>
        </p>
    <% end %>
<% end %>

<%= link_to 'Edit', edit_ironing_path(@ironing) %> |
<%= link_to 'Back', ironing_index_path %>